=== Alan1492/web-stack-lab-assignment-4/bikerrental.dtd
<!ELEMENT bikeRental (bike+)>
<!ELEMENT bike (name, rentalDate, returnDate, rentalPrice, renterName, location)>
<!ATTLIST bike id ID #REQUIRED type CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT rentalDate (#PCDATA)>
<!ELEMENT returnDate (#PCDATA)>
<!ELEMENT rentalPrice (#PCDATA)>
<!ELEMENT renterName (#PCDATA)>
<!ELEMENT location (#PCDATA)>

=== Alan1492/web-stack-lab-assignment-4/bike.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="bike.xsl"?>
<!DOCTYPE bikeRental SYSTEM "bikerrental.dtd">
<bikeRental xmlns="http://www.bikerental.com"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.bikerental.com bikerrental.xsd">

    <bike id="B1" type="mountain">
        <name>Mountain Bike</name>
        <rentalDate>2024-08-10</rentalDate>
        <returnDate>2024-08-11</returnDate>
        <rentalPrice>25.00</rentalPrice>
        <renterName>john doe</renterName>
        <location>Downtown</location>
    </bike>
    <bike id="B2" type="road">
        <name>Road bike</name>
        <rentalDate>2024-08-15</rentalDate>
        <returnDate>2024-08-16</returnDate>
        <rentalPrice>30.00</rentalPrice>
        <renterName>jane smith</renterName>
        <location>uptown</location>
    </bike>
</bikeRental>
